import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import SideNav from "./_components/navigation/SideNav";
export const metadata: Metadata = {
  title: "Create T3 App",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/favicon.ico" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <div className="flex h-screen overflow-hidden bg-stone-900 text-white">
            <SideNav />
            <main className="flex h-screen overflow-hidden bg-stone-900 text-white">
              {children}
              {/* <ReactQueryDevtoolsPanel /> */}
            </main>
          </div>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
